<div class="row">
	
	
	<div class="col-sm-12 col-md-5" >
		<div class="col-sm-12 table-responsive">
			<table class="table table-hover table-condensed table-bordered text-center text-12" id="table-record">
				<thead class="bg-primary">
					<tr>
						<th>No</th>
						<th>Ingeniero</th>
						<th>Gerencia</th>
						<th>Evaluaciones</th>
					</tr>
				</thead>
				<tbody>
					
				</tbody>
			</table>
		</div>
	</div>

	<div class="col-sm-12 col-md-6" >
	
		<div class="col-sm-12 table-responsive">
			<table class="table table-hover table-condensed table-bordered text-center text-12" id="table-record-detalle">
				<thead class="bg-primary">
					<tr>
						<th>No</th>
						<th>Ele</th>
						<th>Descripcion</th>
						<th>Estatus</th>
					</tr>
				</thead>
				<tbody>
					
				</tbody>
			</table>
		</div>

	</div>

	<div class="row col-sm-12">
		
		<div class="col-sm-6" id="indicador-etapa">
					
		</div>
		<div class="col-sm-6" id="indicador-tiempos">
			
		</div>

	</div>

</div>