<div class="row" id="row-evaluaciones-proceso">

	<div class="col-sm-12" style="margin-bottom: 20px; font-size: 11px">

		<table class="table table-bordered" id="table-nuevo">
			<thead>
				<tr>
					<th>Productos Nuevos</th>
					<th id="total_nuevo" ></th>
					<th>Equipos, Proveedores, Materiales (Nuevos)</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
		</table>
		
		<table class="table table-bordered" id="table-existente">
			<thead>
				<tr>
					<th>Equipos Existentes</th>
					<th id="total_existente"></th>
					<th>Mantenimiento, Infraestructura, Actualizaciones Sw y Documentos</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
		</table>

		<table>
			<thead>
				<div id="total">
					<tr>
						<th>Total General</th>
						<th><strong id="total_general"></strong></th>
						<th>-</th>
					</tr>
				</div>
			</thead>
			<tbody>
				
			</tbody>
		</table>
	</div>

	<div class="col-sm-12" style="font-size: 11px">
		
		<table class="table table-bordered" id="table-solicitante">
			<thead>
				<tr>
					<th>Área solicitante Nuevos</th>
					<th>Proyecto</th>
					<th>Mercado</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
		</table>

	</div>

	<div class="col-sm-12" style="font-size: 11px">
		<table class="table table-bordered table-striped" id="table-general">
			<thead>
				<tr>
					<th>No</th>
					<th>Proyecto</th>
					<th>Tipo</th>
					<th>Descripción</th>
					<th>Proveedor</th>
					<th>Estado</th>
					<th>Fecha Compromiso</th>
					<th>Observaciones</th>
					<th>Solicitante</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
		</table>
	</div>

</div>