<div class="row" id="row-table-intervalos">

	<div class="col-md-8 col-md-offset-2 col-sm-12 tableFixHead" style="margin-bottom: 20px;">
		<table class="table table-bordered" id="table-intervalos">
			<thead class="text-capitalize">
				<tr class="text-12">
					<th>Tipo de Evaluación</th>
					<th>Clasificación</th>
					<!-- <th colspan="3">Tiempos</th>
					<th>Fuera de Tiempo</th> -->
					<th class="bg-success1"></th>
					<th class="bg-warning1"></th>
					<th class="bg-danger1"></th>
					<th class="bg-danger2">Fuera de tiempo</th>
					<th>Totales</th>
				</tr>
			</thead>
			<tbody class="text-12">
				<tr class="bg-warning text-center">
					<td colspan="7" >Evaluaciones EN PROCESO</td>
				</tr>
				<!-- EQUIPOS -->
				<tr>
					<td rowspan='4'>Módem, ONT, AP</td>
					<td rowspan="2">Nuevo</td>
					<td class="item">'1-15</td>
					<td class="item">'16-30</td>
					<td class="item">'31-45</td>
					<td class="item">' > 45</td>
					<td></td>
				</tr>
				<tr data-title="Equipos Nuevo 1-45">
					<td class="item action" data-max="45" id="equipos-nue-1-15"></td>
					<td class="item action" data-max="45" id="equipos-nue-16-30"></td>
					<td class="item action" data-max="45" id="equipos-nue-31-45"></td>
					<td class="item action" data-max="45" id="equipos-nue-45"></td>
					<td class="item action" data-max="45" id="equipos-nue-total"></td>
				</tr>
				<tr>
					<td rowspan="2">Software de mantenimiento</td>
					<td class="item">'1-10</td>
					<td class="item">'11-20</td>
					<td class="item">'21-30</td>
					<td class="item">' > 30</td>
					<td></td>
				</tr>
				<tr data-title="Equipos Software 1-30">
					<td class="item action" data-max="30" id="equipos-act-1-10"></td>
					<td class="item action" data-max="30" id="equipos-act-11-20"></td>
					<td class="item action" data-max="30" id="equipos-act-21-30"></td>
					<td class="item action" data-max="30" id="equipos-act-30"></td>
					<td class="item action" data-max="30" id="equipos-act-total"></td>
				</tr>
				<!-- EQUIPOS -->


				<!-- MATERIALES -->
				<tr>
					<td rowspan='4'>Materiales</td>
					<td rowspan="2">CIDEC</td>
					<td class="item">'1-20</td>
					<td class="item">'21-40</td>
					<td class="item">'41-60</td>
					<td class="item">'>60</td>
					<td></td>
				</tr>

				<tr data-title="Materiales CIDEC 1-60">
					<td class="item action" data-max="60" id="materiales-cidec-1-20"></td>
					<td class="item action" data-max="60" id="materiales-cidec-21-40"></td>
					<td class="item action" data-max="60" id="materiales-cidec-41-60"></td>
					<td class="item action" data-max="60" id="materiales-cidec-60"></td>
					<td class="item action" data-max="60" id="materiales-cidec-total"></td>
				</tr>

				<tr>
					<td rowspan="2">Local</td>
					<td class="item">'1-5</td>
					<td class="item">'6-10</td>
					<td class="item">'11-15</td>
					<td class="item">'>15</td>
					<td></td>
				</tr>
				<tr data-title="Materiales local 1-15">
					<td class="item action" data-max="15" id="materiales-local-1-5"></td>
					<td class="item action" data-max="15" id="materiales-local-6-10"></td>
					<td class="item action" data-max="15" id="materiales-local-11-15"></td>
					<td class="item action" data-max="15" id="materiales-local-15"></td>
					<td class="item action" data-max="15" id="materiales-local-total"></td>
				</tr>
				<!-- MATERIALES -->


				<!-- DOCUMENTOS FOAS -->

				<tr>
					<td rowspan='2'>Documentos y FOAs</td>
					<td rowspan="2">TODAS</td>
					<td class="item">'1-5</td>
					<td class="item">'6-10</td>
					<td class="item">'11-15</td>
					<td class="item">'>15</td>
					<td></td>
				</tr>

				<tr data-title="Documentos 1-15">
					<td class="item action" data-max="15" id="docs-1-5"></td>
					<td class="item action" data-max="15" id="docs-6-10"></td>
					<td class="item action" data-max="15" id="docs-11-15"></td>
					<td class="item action" data-max="15" id="docs-15"></td>
					<td class="item action" data-max="15" id="docs-total"></td>
				</tr>

				<!-- DOCUMENTOS FOAS -->

				<!-- FUNCIONALIDAD -->

				<tr>
					<td rowspan="2">Funcionalidad y Pruebas de Concepto</td>
					<td rowspan="2">TODAS</td>
					<td class="item">'1-10</td>
					<td class="item">'11-20</td>
					<td class="item">'21-30</td>
					<td class="item">' > 30</td>
					<td></td>
				</tr>
				<tr data-title="Funcionalidad y Pruebas de Concepto 1-30">
					<td class="item action" data-max="30" id="func-1-10"></td>
					<td class="item action" data-max="30" id="func-11-20"></td>
					<td class="item action" data-max="30" id="func-21-30"></td>
					<td class="item action" data-max="30" id="func-30"></td>
					<td class="item action" data-max="30" id="func-total"></td>
				</tr>

				<!-- FUNCIONALIDAD -->



				<!-- CARACTERIZACIONES -->
				<tr>
					<td rowspan='4'>Caracterizaciones, Interoperabilidad, Equipos, Plataformas, Servicio, Software</td>
					<td rowspan="2">Nuevo</td>
					<td class="item">'1-20</td>
					<td class="item">'21-40</td>
					<td class="item">'41-60</td>
					<td class="item">'>60</td>
					<td></td>
				</tr>

				<tr data-title="Caracterizaciones, Interoperabilidad, Equipos, Plataformas, Servicio, Software NUEVOS 1-60">
					<td class="item action" data-max="60" id="caract-nue-1-20"></td>
					<td class="item action" data-max="60" id="caract-nue-21-40"></td>
					<td class="item action" data-max="60" id="caract-nue-41-60"></td>
					<td class="item action" data-max="60" id="caract-nue-60"></td>
					<td class="item action" data-max="60" id="caract-nue-total"></td>
				</tr>

				<tr>
					<td rowspan="2">Actualizaciones</td>
					<td class="item">'1-10</td>
					<td class="item">'11-20</td>
					<td class="item">'21-30</td>
					<td class="item">' > 30</td>
					<td></td>
				</tr>
				<tr data-title="Caracterizaciones, Interoperabilidad, Equipos, Plataformas, Servicio, Software ACTUALIZACIONES 1-60">
					<td class="item action" data-max="30" id="caract-act-1-10"></td>
					<td class="item action" data-max="30" id="caract-act-11-20"></td>
					<td class="item action" data-max="30" id="caract-act-21-30"></td>
					<td class="item action" data-max="30" id="caract-act-30"></td>
					<td class="item action" data-max="30" id="caract-act-total"></td>
				</tr>
				<!-- CARACTERIZACIONES -->




				<!-- ESPECIFICACIONES -->
				<tr>
					<td rowspan='4'>Especificaciones</td>
					<td rowspan="2">Nuevo</td>
					<td class="item">'1-30</td>
					<td class="item">'31-60</td>
					<td class="item">'61-90</td>
					<td class="item">'>90</td>
					<td></td>
				</tr>

				<tr data-title="Especificaciones nuevas 1-90">
					<td class="item action" data-max="90" id="espec-nue-1-30"></td>
					<td class="item action" data-max="90" id="espec-nue-31-60"></td>
					<td class="item action" data-max="90" id="espec-nue-61-90"></td>
					<td class="item action" data-max="90" id="espec-nue-90"></td>
					<td class="item action" data-max="90" id="espec-nue-total"></td>
				</tr>

				<tr>
					<td rowspan="2">Actualizaciones</td>
					<td class="item">'1-10</td>
					<td class="item">'11-20</td>
					<td class="item">'21-30</td>
					<td class="item">' > 30</td>
					<td></td>
				</tr>
				<tr data-title="Especificaciones actualización 1-30">
					<td class="item action" data-max="30" id="espec-act-1-10"></td>
					<td class="item action" data-max="30" id="espec-act-11-20"></td>
					<td class="item action" data-max="30" id="espec-act-21-30"></td>
					<td class="item action" data-max="30" id="espec-act-30"></td>
					<td class="item action" data-max="30" id="espec-act-total"></td>
				</tr>
				<!-- ESPECIFICACIONES -->

				<!-- PROYECTOS ESPECIALES -->

				<tr>
					<td colspan='2' rowspan="2">Proyectos Especiales</td>
					<td class="item"> - </td>
					<td class=""> - </td>
					<td class=""> - </td>
					<td class=""> - </td>
					<td></td>
				</tr>

				<tr data-title="Proyectos Especiales">
					<td class="item action" data-max="especial" id="especiales-1-5"></td>
					<td class="item" data-max="especial" id="especiales-6-10"></td>
					<td class="item" data-max="especial" id="especiales-11-15"></td>
					<td class="item" data-max="especial" id="especiales-15"></td>
					<td class="item" data-max="especial" id="especiales-total"></td>
				</tr>

				<!-- PROYECTOS ESPECIALES -->


				<tr data-title="Total por periodo">
					<td colspan="2">Total Evaluaciones en PROCESO</td>
					<td class="item action-total" id="total-1"></td>
					<td class="item action-total" id="total-2"></td>
					<td class="item action-total" id="total-3"></td>
					<td class="item action-total" id="total-4"></td>
					<td class="item" id="proceso-total"></td>
				</tr>

				
				<!-- SOLICITUDES NUEVAS -->

				<tr class="bg-info">
					<td colspan="6">Total Evaluaciones en NUEVA SOLICITUD (sin información suficiente para asignar a un rubro)</td>
					<td rowspan="2" class="item" id="nuevas-total"></td>
				</tr>

				<!-- SOLICITUDES NUEVAS -->


			</tbody>
		</table>
	</div>

</div>


<!-- Modal Editar-->
	<div class="col-sm-12">
		<div class="modal fade" id="modal-intervalos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			<div class="modal-dialog modal-lg" role="document">
				<div class="modal-content">
					<div class="modal-header bg-primary">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="modal-head-title"></h4>
					</div>
					<div class="modal-body">
						<div class="row">
							
							<table class="table table-bordered" id="table-intervalos-detalle">
								<thead>
									<tr>
										<td>No.</td>
										<td>Ele</td>
										<td>Descripción</td>
										<td>Gerencia</td>
										<td>Subgerente</td>
										<td>Fecha de solicitud</td>
										<td>Días transcurridos</td>
										<td>Vence</td>
									</tr>
								</thead>
								<tbody class="text-12">
									
								</tbody>
							</table>

						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">cerrar</button>
						<!-- <button type="button" class="btn btn-primary" id="btn-guardar-eval">Guardar</button> -->
					</div>
				</div>
			</div>
		</div>
	</div>